// Generated by scripts/build_guides.py from docs/user-training.md — do not edit.
//
// The Guide for the user app has one source: that document. Edit the
// document, run `python scripts/build_guides.py`, and commit both. A Guide that
// can drift from the training document is two documents, and the second one is
// the one nobody maintains — `scripts/check_docs.sh` fails when they disagree.

import type { GuideSection } from "./guide";

export const GUIDE: GuideSection[] = [
  {
    "id": "s1",
    "title": "What the tool is doing for you",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "You upload the order's requirement spec (the "
          },
          {
            "text": "OSL",
            "bold": true
          },
          {
            "text": ", a Word document), the ETL configuration (JSON), and the output reports (Excel). The tool reads the OSL, works out what it requires, traces each requirement into the configuration and then into the reports, and shows you a list of "
          },
          {
            "text": "findings",
            "bold": true
          },
          {
            "text": ": places where the three disagree. The model reads and judges meaning; every comparison of values, counts, and ranges is done by code, so a finding is exact and repeatable. You decide each finding, OK or Not OK, and generate a frozen one-page report with a PDF."
          }
        ]
      }
    ]
  },
  {
    "id": "s2",
    "title": "What matters most from you",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "Most of the form is identification: it labels the run so somebody can find it again. Three things change what the tool finds, and they are worth real care."
          }
        ]
      },
      {
        "kind": "ordered",
        "items": [
          [
            {
              "text": "The delivery programme.",
              "bold": true
            },
            {
              "text": " It decides which rules apply and what the tool expects to see. Get it wrong and you will either be shown findings that were never relevant to this delivery, or miss the ones that were. If the list does not obviously contain your delivery, ask rather than guess — and the tool reads the artifacts a second time to check they look like the programme you chose, so a mismatch is usually caught."
            }
          ],
          [
            {
              "text": "The delivery notes.",
              "bold": true
            },
            {
              "text": " One sentence of context here improves what the tool finds more than anything else you can type. It is read as background, never as a requirement, so it cannot make a delivery pass — it helps the tool understand what it is looking at. "
            },
            {
              "text": "\"The state list was cut to four states at the customer's request on the 14th\"",
              "italic": true
            },
            {
              "text": " saves a reviewer three findings and a phone call."
            }
          ],
          [
            {
              "text": "The right files.",
              "bold": true
            },
            {
              "text": " The tool checks the configuration id, the customer and the credit date against what the artifacts themselves say, before it starts, and holds the run when they disagree. That check costs nothing and catches the expensive mistake, but it can only compare what you gave it: the wrong report for the right order still looks consistent."
            }
          ]
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "Everything else on the form — the order number, your own reference — identifies the run and is never sent to the model. The marker under each box says which kind it is."
          }
        ]
      }
    ]
  },
  {
    "id": "s3",
    "title": "When the tool is unsure",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "The word does three jobs in this tool, and mixing them up is the commonest confusion."
          }
        ]
      },
      {
        "kind": "table",
        "head": [
          [
            {
              "text": "Where you see it"
            }
          ],
          [
            {
              "text": "What it means"
            }
          ]
        ],
        "rows": [
          [
            [
              {
                "text": "Needs review",
                "bold": true
              },
              {
                "text": " — a run's status"
              }
            ],
            [
              {
                "text": "The pipeline has finished and the findings are waiting for you. It is not a verdict; it is \"your turn\"."
              }
            ]
          ],
          [
            [
              {
                "text": "review",
                "bold": true
              },
              {
                "text": " — a finding's severity"
              }
            ],
            [
              {
                "text": "The tool is "
              },
              {
                "text": "not confident",
                "italic": true
              },
              {
                "text": " about this one. Something did not extract cleanly, or a second reading disagreed with the first. It is asking you to look, not telling you something is wrong. Treat it as a question."
              }
            ]
          ],
          [
            [
              {
                "text": "Reviewing findings",
                "bold": true
              },
              {
                "text": " — what you do"
              }
            ],
            [
              {
                "text": "Deciding each finding OK or Not OK, with a comment. This is the judgement the whole tool exists to support."
              }
            ]
          ]
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "The middle row is the one worth remembering: "
          },
          {
            "text": "a `review` severity is the tool being honest about uncertainty, not an accusation.",
            "bold": true
          },
          {
            "text": " A finding it is sure about is high, medium or low. A finding it is unsure about says so rather than guessing, because a confident wrong answer costs more than an admitted doubt."
          }
        ]
      }
    ]
  },
  {
    "id": "s4",
    "title": "How to read a finding, and how to decide",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "The run page shows the "
          },
          {
            "text": "traceability matrix",
            "bold": true
          },
          {
            "text": " and the "
          },
          {
            "text": "findings",
            "bold": true
          },
          {
            "text": ", worst first."
          }
        ]
      },
      {
        "kind": "list",
        "items": [
          [
            {
              "text": "Each finding has a "
            },
            {
              "text": "severity",
              "bold": true
            },
            {
              "text": " (high, medium, low, or review), a title that says what disagrees with what, the evidence from all three artefacts side by side, and an OK / Not OK decision with a comment."
            }
          ],
          [
            {
              "text": "There are three decisions. "
            },
            {
              "text": "False positive",
              "bold": true
            },
            {
              "text": " means the finding is not a real problem. "
            },
            {
              "text": "Accepted risk",
              "bold": true
            },
            {
              "text": " means it is real and the delivery goes ahead anyway, and it always needs a comment saying why. "
            },
            {
              "text": "Not OK",
              "bold": true
            },
            {
              "text": " means the delivery has to change, and on a high or review finding it needs a comment too. The tool says so before it records anything, so nothing you typed is lost."
            }
          ],
          [
            {
              "text": "Low-severity findings can be marked OK in bulk, as false positives. High-severity ones never can: every one must be decided by hand before the report can be generated."
            }
          ],
          [
            {
              "text": "Generate final report asks once",
              "bold": true
            },
            {
              "text": ", showing the finding counts and reminding you that freezing is permanent: the report is stored once, never regenerated, and the findings can no longer be re-reviewed."
            }
          ]
        ]
      }
    ]
  },
  {
    "id": "s5",
    "title": "How to tell a clean delivery from an unexamined one",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "Above the findings is a panel headed "
          },
          {
            "text": "What was checked",
            "bold": true
          },
          {
            "text": ". It exists because a short findings list cannot tell a clean delivery from one nobody examined, and that is how a compliance requirement slips through: nothing disagreed with it because nothing was compared against it."
          }
        ]
      },
      {
        "kind": "list",
        "items": [
          [
            {
              "text": "Every requirement is in one of four states. "
            },
            {
              "text": "Checked against a report",
              "bold": true
            },
            {
              "text": " means a check compared it with the delivery. "
            },
            {
              "text": "Traced, no report evidenced it",
              "bold": true
            },
            {
              "text": " means it reached the configuration and no report shows it was applied. "
            },
            {
              "text": "Not traced",
              "bold": true
            },
            {
              "text": " means nothing implements it, which is already a finding. "
            },
            {
              "text": "Verified by hand",
              "bold": true
            },
            {
              "text": " means no check can express it, or the check for it could not be run."
            }
          ],
          [
            {
              "text": "The panel also warns when a report arrived and "
            },
            {
              "text": "no check examined it",
              "bold": true
            },
            {
              "text": ", which usually means that report type has no guide, meaning entry or named value yet."
            }
          ],
          [
            {
              "text": "\"Declared as X; some words point to Y\"",
              "bold": true
            },
            {
              "text": " is the tool saying it is unsure which programme this delivery is, not that you were wrong. It appears when none of your programme's usual words are in the documents and a few of another programme's are — which happens honestly, for instance when a solicitation says it excludes existing accounts. Confirm the programme is right and mark it OK; if it keeps happening for a customer, ask your administrator to add that customer's wording to the programme."
            }
          ],
          [
            {
              "text": "Notices",
              "bold": true
            },
            {
              "text": " appear here too: a second opinion the model could not give, a programme reading that did not run. They are not findings, and you should know about them."
            }
          ],
          [
            {
              "text": "Every requirement nothing evidenced, and every check that could not be evaluated, needs "
            },
            {
              "text": "I have seen this",
              "bold": true
            },
            {
              "text": " before the report can be frozen. That is not you saying the delivery is fine. It is the record that the gap was in front of you, and it goes into the frozen report with your name on it. Add a note if you raised it with someone."
            }
          ]
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "If several readers looked at a finding, the evidence panel shows "
          },
          {
            "text": "how it was read",
            "bold": true
          },
          {
            "text": ": each reader, whether it agreed, and why. They each saw the same evidence and none saw the others."
          }
        ]
      },
      {
        "kind": "list",
        "items": [
          [
            {
              "text": "If a requirement was extracted wrongly, edit it and press "
            },
            {
              "text": "Re-check",
              "bold": true
            },
            {
              "text": ". Only the comparison stages re-run; nothing is re-asked of the model that has not changed."
            }
          ],
          [
            {
              "text": "Configuration notes given to the model",
              "bold": true
            },
            {
              "text": " appear above the findings when the configuration had any. This is what the model was told as background; it is shown so you can judge a finding knowing the context behind it."
            }
          ],
          [
            {
              "text": "Since the previous run",
              "bold": true
            },
            {
              "text": " appears when an earlier run of the same configuration id was finalized for this customer. It lists Not OK items from last time that are back (read these first), findings that are new and findings that went away, and what changed in the requirements and the configuration. Compared by code; the model is not involved. The same section is frozen into the report."
            }
          ]
        ]
      }
    ]
  },
  {
    "id": "s6",
    "title": "What it will not catch",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "A tool whose limits are written down is trusted correctly rather than uniformly, and a reviewer who believes it catches everything is the exact failure this product exists to prevent. So, plainly:"
          }
        ]
      },
      {
        "kind": "list",
        "items": [
          [
            {
              "text": "It compares three documents. It does not check the world.",
              "bold": true
            },
            {
              "text": " If the OSL itself asks for the wrong thing, every artifact can agree with it and nothing will be raised."
            }
          ],
          [
            {
              "text": "It cannot see what nobody wrote down.",
              "bold": true
            },
            {
              "text": " A verbal agreement with the customer, a decision in an email, a convention everyone in the team knows — none of it reaches the tool unless it is in the OSL, the configuration, or your delivery notes."
            }
          ],
          [
            {
              "text": "A requirement no check can express is marked as needing a person",
              "bold": true
            },
            {
              "text": ", not silently passed. "
            },
            {
              "text": "What was checked",
              "italic": true
            },
            {
              "text": " lists those, and they are yours."
            }
          ],
          [
            {
              "text": "It reads a sample of rows, not the whole file",
              "bold": true
            },
            {
              "text": ", for anything a person's judgement would be needed for. Volume checks are done by code over counts; the tool does not re-derive every row of a delivery."
            }
          ],
          [
            {
              "text": "A finding it is unsure about says so.",
              "bold": true
            },
            {
              "text": " Treat a "
            },
            {
              "text": "review",
              "code": true
            },
            {
              "text": " severity as a question. It is not the tool hedging on something it knows."
            }
          ],
          [
            {
              "text": "Nothing it says is a sign-off.",
              "bold": true
            },
            {
              "text": " It reports where three documents disagree. Whether the delivery is acceptable has your name on it, not the tool's."
            }
          ]
        ]
      }
    ]
  },
  {
    "id": "s7",
    "title": "Why your disagreement is worth recording",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "When you mark a finding a false positive, or say in your own words what the tool should have expected, that sentence does not stop at your screen. An administrator reads it, and where it can become a rule the tool drafts one — which then runs "
          },
          {
            "text": "silently",
            "bold": true
          },
          {
            "text": " beside the real checks until there are enough results to know whether it is any good. Only then can it start producing findings anybody sees."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "Two things follow that are worth knowing. Your sentence is worth writing carefully, because a person will read it and it may end up as a rule. And you find out what happened to it: your observations screen says whether it became a rule, is still being measured, or was not taken forward, with the reason."
          }
        ]
      }
    ]
  },
  {
    "id": "s8",
    "title": "Why the Admin console link may not be there",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "The sidebar offers an "
          },
          {
            "text": "Admin console",
            "bold": true
          },
          {
            "text": " link only to accounts that include it. If you do not see it, your account is a user account: submitting runs and deciding findings is the whole job, and there is nothing in the console you would be able to change. Ask an administrator if you think that is wrong — a senior associate who approves what the tool has learned is usually given the reviewer role as well, which does show the link."
          }
        ]
      }
    ]
  },
  {
    "id": "s9",
    "title": "Getting help",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "Your administrator can see every setting, every rule, and every observation in the admin console. If a finding surprises you, the "
          },
          {
            "text": "Rules",
            "bold": true
          },
          {
            "text": " screen there says what made it fire."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "If a run "
          },
          {
            "text": "failed",
            "bold": true
          },
          {
            "text": ", open it and copy the "
          },
          {
            "text": "Technical detail",
            "bold": true
          },
          {
            "text": " block into your message. It names the stage and carries the traceback, and it saves the first round of questions."
          }
        ]
      }
    ]
  }
];
