// Generated by scripts/build_guides.py from docs/admin-training.md — do not edit.
//
// The Guide for the admin console has one source: that document. Edit the
// document, run `python scripts/build_guides.py`, and commit both. A Guide that
// can drift from the training document is two documents, and the second one is
// the one nobody maintains — `scripts/check_docs.sh` fails when they disagree.

import type { GuideSection } from "./guide";

export const GUIDE: GuideSection[] = [
  {
    "id": "s1",
    "title": "What an administrator is responsible for",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "Three things, in order of how often they come up."
          }
        ]
      },
      {
        "kind": "ordered",
        "items": [
          [
            {
              "text": "Keeping the tool honest about what it checks",
              "bold": true
            },
            {
              "text": ": the artifact types it accepts, the samples it learns layouts from, the rules it runs, and their state."
            }
          ],
          [
            {
              "text": "Turning what reviewers know into rules",
              "bold": true
            },
            {
              "text": ", through the training queue, with a person at every gate."
            }
          ],
          [
            {
              "text": "Operating it",
              "bold": true
            },
            {
              "text": ": accounts, the model, throughput, retention, and the settings that used to live in "
            },
            {
              "text": ".env",
              "code": true
            },
            {
              "text": "."
            }
          ]
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "Everything you change is audited with your name, and most of it takes effect on the next request or the next run, with no restart."
          }
        ]
      }
    ]
  },
  {
    "id": "s2",
    "title": "The front door, and which surface a thing belongs on",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "The first item in the sidebar, and the one to reach for when you are not sure which of the other screens a thing belongs on. Write "
          },
          {
            "text": "one",
            "bold": true
          },
          {
            "text": " statement in your own words — \"the account review file must never have a blank origination date\", \"billing count must never exceed the delivered count\" — choose where it applies, and press "
          },
          {
            "text": "Tell the tool",
            "bold": true
          },
          {
            "text": "."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "What happens next is the training loop, not a new one. The tool decides which existing surface the statement belongs on, drafts the rule there, and puts it in the queue as an ordinary candidate. "
          },
          {
            "text": "Nothing runs until you approve it",
            "bold": true
          },
          {
            "text": ", and an approved rule starts in shadow like any other."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "Three answers are possible, and two of them create nothing:"
          }
        ]
      },
      {
        "kind": "list",
        "items": [
          [
            {
              "text": "A candidate.",
              "bold": true
            },
            {
              "text": " It names the surface and shows the draft, with a link into the queue where you approve or reject it as usual."
            }
          ],
          [
            {
              "text": "Background.",
              "bold": true
            },
            {
              "text": " Some things are worth the tool knowing but are not something a delivery can pass or fail — \"the second tab is the reissue file\". The tool says so and points you at the artifact type's AI context or the standing instructions. It does not turn it into a rule that would then be wrong."
            }
          ],
          [
            {
              "text": "A question.",
              "bold": true
            },
            {
              "text": " When the statement could be two things, or names nothing the tool can check, you get the question back and nothing is created. That is the answer working, not failing: a rule on the wrong surface is a finding nobody can explain."
            }
          ]
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "Occasionally the tool reads a statement one way and drafts it another. It says so instead of hiding it, and that is your cue to read the draft carefully before approving."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "This screen does not replace the ones below. They are the expert view, they show exactly what runs, and they stay the place where things are really managed."
          }
        ]
      },
      {
        "kind": "heading",
        "spans": [
          {
            "text": "Which screen holds what"
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "The front door answers this for you most of the time. When you want to go straight to the right screen, these are the three groups that genuinely overlap, and what actually separates them."
          }
        ]
      },
      {
        "kind": "table",
        "head": [
          [
            {
              "text": "These all do the same job"
            }
          ],
          [
            {
              "text": "And differ in"
            }
          ]
        ],
        "rows": [
          [
            [
              {
                "text": "Validation guides, meaning entries, named values"
              }
            ],
            [
              {
                "text": "how they locate a cell in a report"
              }
            ]
          ],
          [
            [
              {
                "text": "Programme rules, compliance rules, judgment checks"
              }
            ],
            [
              {
                "text": "who evaluates \"this must hold\": the model reading, code comparing, or the configuration being present"
              }
            ]
          ],
          [
            [
              {
                "text": "An artifact type's AI context, standing instructions, configuration notes"
              }
            ],
            [
              {
                "text": "nothing, at the prompt — all three reach the model as background. Choose by how wide it is: one artifact type, one programme, one configuration"
              }
            ]
          ],
          [
            [
              {
                "text": "An artifact type's AI context, a worked example"
              }
            ],
            [
              {
                "text": "whether you are telling the model something about this work, or showing it a finished answer to copy the shape of. Neither is a rule"
              }
            ]
          ]
        ]
      }
    ]
  },
  {
    "id": "s3",
    "title": "Setting up a new delivery, and which steps help the AI",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "Two cards at the top of Artifact types, which is the console's home."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "Setting up a new delivery",
            "bold": true
          },
          {
            "text": " is the order the screens are usually used in — say which reports exist, upload a sample of each, record what this delivery calls things, explain what the numbers mean, map the requirements, write the checks, set up the programmes — with a tick beside each step that is done. It is a checklist, not a wizard: it hides nothing, forces no order, and every step is a link to the screen that already does the job. Each step says "
          },
          {
            "text": "why",
            "italic": true
          },
          {
            "text": " it matters, because a reason is what makes somebody do a step properly rather than tick it."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "The card itself does nothing to a run.",
            "bold": true
          },
          {
            "text": " It is a path through screens: it reads what already exists to work out which steps are done, and it reaches no prompt, feeds no comparison, and is stored nowhere. Asking whether the checklist helps the AI is asking about the signpost rather than the road."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "The seven steps are not alike, and each one now says which it is,",
            "bold": true
          },
          {
            "text": " with the same marker the screen it links to already carries:"
          }
        ]
      },
      {
        "kind": "table",
        "head": [
          [
            {
              "text": "Step"
            }
          ],
          [
            {
              "text": "Marker"
            }
          ],
          [
            {
              "text": "Because"
            }
          ]
        ],
        "rows": [
          [
            [
              {
                "text": "Say which reports the delivery has"
              }
            ],
            [
              {
                "text": "Checked by code"
              }
            ],
            [
              {
                "text": "Code matches each uploaded workbook against the list. Only where two types score alike is the model shown their labels, and only from the shortlist code already made."
              }
            ]
          ],
          [
            [
              {
                "text": "Upload a sample of each"
              }
            ],
            [
              {
                "text": "Used for setup, not for runs"
              }
            ],
            [
              {
                "text": "The AI reads samples while you set up — type detection, example values, the mapping interview. No sample is opened when a delivery is checked."
              }
            ]
          ],
          [
            [
              {
                "text": "Record what this delivery calls things"
              }
            ],
            [
              {
                "text": "Checked by code"
              }
            ],
            [
              {
                "text": "A spelling recorded here resolves the name in code, before any model call."
              }
            ]
          ],
          [
            [
              {
                "text": "Explain what the numbers mean"
              }
            ],
            [
              {
                "text": "Helps the AI",
                "bold": true
              }
            ],
            [
              {
                "text": "Guide entries are read at tracing and verification, so the model knows what a cell is for rather than guessing from its label."
              }
            ]
          ],
          [
            [
              {
                "text": "Map the requirements to the configuration"
              }
            ],
            [
              {
                "text": "Helps the AI",
                "bold": true
              }
            ],
            [
              {
                "text": "Meaning entries are read at tracing and verification as background — and a confirmed row with a configuration path also compiles into a comparison code makes itself."
              }
            ]
          ],
          [
            [
              {
                "text": "Write the checks a formula can express"
              }
            ],
            [
              {
                "text": "Checked by code"
              }
            ],
            [
              {
                "text": "Evaluated on every run in scope at no token cost, and the same inputs always give the same answer."
              }
            ]
          ],
          [
            [
              {
                "text": "Set up the delivery programmes"
              }
            ],
            [
              {
                "text": "Helps the AI",
                "bold": true
              }
            ],
            [
              {
                "text": "Standing instructions are background on every run in the programme, and the model reads each programme rule and says whether it holds — code sets how serious that is."
              }
            ]
          ]
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "So three of the seven change what the model is shown, three are code and reach no prompt at all, and one is read only while you are setting up. That is worth knowing before you decide where an afternoon goes: the three marked "
          },
          {
            "text": "Helps the AI",
            "bold": true
          },
          {
            "text": " are the ones that change what a run "
          },
          {
            "text": "finds",
            "italic": true
          },
          {
            "text": ", and the three marked "
          },
          {
            "text": "Checked by code",
            "bold": true
          },
          {
            "text": " are the ones that change what it can "
          },
          {
            "text": "measure",
            "italic": true
          },
          {
            "text": ". Neither is better; they answer different questions. "
          },
          {
            "text": "docs/model-context.md",
            "code": true
          },
          {
            "text": " is the register these markers quote, and the marker on the samples is the one you can switch off in Settings (ADR-046)."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "Try this setup",
            "bold": true
          },
          {
            "text": " runs everything code can run against the sample workbooks already stored and says what happened: which sheets each sample carries and which of the names the checks look for resolved, what every named value found, and what every check would have done. "
          },
          {
            "text": "No AI is called and nothing is saved",
            "bold": true
          },
          {
            "text": ", so press it as often as you like while you work."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "It answers "
          },
          {
            "text": "is this wired up",
            "italic": true
          },
          {
            "text": ". It cannot tell you whether a check asks the right question, and it says so. And a check that does not hold "
          },
          {
            "text": "against a sample",
            "bold": true
          },
          {
            "text": " has found nothing wrong with anything — the samples are specimens, not deliveries; it tells you the check runs."
          }
        ]
      }
    ]
  },
  {
    "id": "s4",
    "title": "What improves the QC, in the order it pays off",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "Six things are worth your time, and they are not equally worth it. In order:"
          }
        ]
      },
      {
        "kind": "ordered",
        "items": [
          [
            {
              "text": "Accepting attribute suggestions.",
              "bold": true
            },
            {
              "text": " After a run, Reference data lists what the tool worked out that delivery calls each attribute it could not locate — mostly read straight out of the uploaded record layout, in code, with no AI involved. Each one you accept resolves that name in code on every later run of that configuration, and turns a requirement nothing checked into a requirement that is checked. It is clicking, not writing, which is why it is first."
            }
          ],
          [
            {
              "text": "Worked examples.",
              "bold": true
            },
            {
              "text": " One example of a judgement the tool got wrong, at the stage it got it wrong, changes its answers on every run afterwards. Nothing else you "
            },
            {
              "text": "write",
              "italic": true
            },
            {
              "text": " has that reach for that little effort."
            }
          ],
          [
            {
              "text": "Artifact guidance and AI context.",
              "bold": true
            },
            {
              "text": " Telling the tool how to read a workbook — which tab is what, which heading row to trust — fixes a whole class of \"could not evaluate\" at once, because a check that cannot find its column is not a check."
            }
          ],
          [
            {
              "text": "Programme keywords in the customer's own vocabulary.",
              "bold": true
            },
            {
              "text": " The keyword check is what confirms a delivery is the programme it claims to be. It matches text, so it only works in words the customer actually uses: add "
            },
            {
              "text": "their",
              "italic": true
            },
            {
              "text": " phrase, not the industry's."
            }
          ],
          [
            {
              "text": "Standing instructions on a programme.",
              "bold": true
            },
            {
              "text": " Background the tool should carry into every run of that programme. Useful, bounded, and read as background rather than as a rule — which is also why it is fifth: it informs answers rather than deciding them."
            }
          ],
          [
            {
              "text": "Masked columns",
              "bold": true
            },
            {
              "text": ", whenever a new layout arrives carrying personal data. This one is not about quality at all; it is the control that has to be right regardless."
            }
          ]
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "What is "
          },
          {
            "text": "not",
            "italic": true
          },
          {
            "text": " on that list: writing more rules. A noisy rule costs a reviewer attention on every run, forever. Sort Rules by dismissal rate before you add another one."
          }
        ]
      }
    ]
  },
  {
    "id": "s5",
    "title": "How to read the numbers",
    "blocks": [
      {
        "kind": "list",
        "items": [
          [
            {
              "text": "Fired and dismissed",
              "bold": true
            },
            {
              "text": ", per rule. Fired is how often it produced a finding; dismissed is how often a person said that finding was not a real problem. The ratio is the number that matters, and a high one means the rule is spending reviewer attention rather than saving it."
            }
          ],
          [
            {
              "text": "Shadow",
              "bold": true
            },
            {
              "text": " means a rule is being evaluated and its findings are recorded but shown to nobody. It is how a rule earns activation: you can see what it "
            },
            {
              "text": "would",
              "italic": true
            },
            {
              "text": " have raised, against real deliveries, before anybody has to read it."
            }
          ],
          [
            {
              "text": "Precision",
              "bold": true
            },
            {
              "text": ", here, means: of the findings this rule raised, how many a person agreed with. It is measured from verdicts people actually gave, so it is only as meaningful as the number of verdicts behind it — a rule with four results has no precision worth quoting."
            }
          ],
          [
            {
              "text": "Review load",
              "bold": true
            },
            {
              "text": " shows what reviewers would stop needing to see. It is "
            },
            {
              "text": "acting on nothing",
              "bold": true
            },
            {
              "text": ": it reports, and no finding is hidden because of it. That is deliberate, and it stays that way until the numbers behind it have been read by a person who can judge them."
            }
          ],
          [
            {
              "text": "Usage",
              "bold": true
            },
            {
              "text": " counts runs per person and per period. It is there to show where the work actually is, not to rank anybody."
            }
          ]
        ]
      }
    ]
  },
  {
    "id": "s6",
    "title": "Who may do what: the three roles",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "An account holds any of three roles, and it can hold several. "
          },
          {
            "text": "What somebody may do is the union of what their roles grant",
            "bold": true
          },
          {
            "text": ", so adding one never takes another away."
          }
        ]
      },
      {
        "kind": "table",
        "head": [
          [
            {
              "text": "Role"
            }
          ],
          [
            {
              "text": "What it is for"
            }
          ]
        ],
        "rows": [
          [
            [
              {
                "text": "user",
                "bold": true
              }
            ],
            [
              {
                "text": "Submits runs and decides findings in the user app. No admin console at all — the link is not even offered."
              }
            ]
          ],
          [
            [
              {
                "text": "reviewer",
                "bold": true
              }
            ],
            [
              {
                "text": "Everything in this console that is about "
              },
              {
                "text": "judging the work",
                "italic": true
              },
              {
                "text": ": approving what the tool learned, the rule surfaces, worked examples, the figures, and the reference data a delivery's vocabulary needs."
              }
            ]
          ],
          [
            [
              {
                "text": "admin",
                "bold": true
              }
            ],
            [
              {
                "text": "All of that, plus what "
              },
              {
                "text": "defines the deployment",
                "italic": true
              },
              {
                "text": ": delivery programmes, artifact types, meaning, accounts, settings, and masked columns."
              }
            ]
          ]
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "The line is between "
          },
          {
            "text": "judging the work",
            "bold": true
          },
          {
            "text": " and "
          },
          {
            "text": "defining the deployment",
            "bold": true
          },
          {
            "text": ". A reviewer decides whether a rule is right. An administrator decides what a programme is, who has an account, and what the tool is allowed to send to a model. Different jobs, different blast radius, and the second group should be much smaller."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "Two things to know when you assign them:"
          }
        ]
      },
      {
        "kind": "list",
        "items": [
          [
            {
              "text": "A senior associate is a user and a reviewer",
              "bold": true
            },
            {
              "text": ", not an administrator. That is the person the whole training loop was built for: they know a programme well enough to approve what the tool learned from it, and they should not be creating accounts or changing what the tool may send to a model."
            }
          ],
          [
            {
              "text": "Masked columns sit on the admin side",
              "bold": true
            },
            {
              "text": " even though the rest of Reference data does not. Naming a column there is what keeps personal data out of every prompt; it is the strongest control in the product and the one whose failure is least visible, because nothing goes wrong on screen when a column stops being masked."
            }
          ]
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "The checkboxes on the Users screen are checkboxes and not a dropdown for a reason: the roles are not exclusive. "
          },
          {
            "text": "You cannot remove the last administrator",
            "bold": true
          },
          {
            "text": ", by unticking the box or by deactivating the account, including your own — locking everybody out of the console cannot be undone without editing the database."
          }
        ]
      },
      {
        "kind": "text",
        "spans": [
          {
            "text": "None of this applies until login is switched on. With it off there is one placeholder account that everything is attributed to, it holds every role, and nothing is gated."
          }
        ]
      }
    ]
  },
  {
    "id": "s7",
    "title": "What is never editable, and why",
    "blocks": [
      {
        "kind": "text",
        "spans": [
          {
            "text": "Four settings are shown read-only on the Settings screen, and no console anywhere can change them: the "
          },
          {
            "text": "database URL",
            "bold": true
          },
          {
            "text": ", the "
          },
          {
            "text": "data directory",
            "bold": true
          },
          {
            "text": ", the "
          },
          {
            "text": "bind address",
            "bold": true
          },
          {
            "text": ", and the "
          },
          {
            "text": "master key",
            "bold": true
          },
          {
            "text": ". Each one is needed to reach or protect the settings store itself. A database URL that lived in the database could be pointed somewhere else and then never read back; a master key stored under its own encryption cannot decrypt itself. They are environment configuration, changed where the service is deployed and nowhere else."
          }
        ]
      }
    ]
  },
  {
    "id": "s8",
    "title": "A weekly routine that keeps the tool honest",
    "blocks": [
      {
        "kind": "ordered",
        "items": [
          [
            {
              "text": "Read the training queue. Reject what cannot be a rule, with reasons; synthesize what can."
            }
          ],
          [
            {
              "text": "Look at shadow rules with their numbers. Activate the ones that have earned it."
            }
          ],
          [
            {
              "text": "Sort Rules by dismissal rate. Narrow or disable the noisy ones."
            }
          ],
          [
            {
              "text": "Check the change history on Settings for anything you did not expect."
            }
          ],
          [
            {
              "text": "Confirm the artifact types still match what customers actually send; add a sample for any layout that surprised the detector."
            }
          ],
          [
            {
              "text": "Clear the attribute suggestions. Each one is a name the tool had to work out and will have to work out again on the next delivery. Watch "
            },
            {
              "text": "attribute lookups per run",
              "bold": true
            },
            {
              "text": " on Usage while you do it: if that number is not falling, the suggestions are not the ones the runs actually need, and the thing to look at is which attributes keep coming back rather than the number itself."
            }
          ]
        ]
      }
    ]
  }
];
