"""initial schema

Revision ID: 5754a730ad63
Revises:
Created: 2026-09-18 13:11:16.353352

Additive changes only, portable across SQLite and Postgres (ADR-017).
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# Autogenerated migrations name our custom column types by their full path, and the
# JSON variant renders as a postgresql dialect type even on SQLite.
import vigilai.db.types
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

revision: str = "5754a730ad63"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribute_aliases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("customer_name", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attribute_aliases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attribute_aliases_alias"), ["alias"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_attribute_aliases_canonical_name"), ["canonical_name"], unique=False
        )

    op.create_table(
        "check_definitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("expression", sa.Text(), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("check_definitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_check_definitions_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_check_definitions_name"), ["name"], unique=False)

    op.create_table(
        "compliance_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "requirement",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("configuration_id", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("customer_name", sa.String(length=200), nullable=False),
        sa.Column(
            "content",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("last_modified", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("configuration_id", "version", name="uq_config_version"),
    )
    with op.batch_alter_table("configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_configs_configuration_id"), ["configuration_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_configs_sha256"), ["sha256"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task", sa.String(length=60), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("run_after", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.Column("locked_by", sa.String(length=100), nullable=False),
        sa.Column("locked_at", vigilai.db.types.Utc(timezone=True), nullable=True),
        sa.Column("created_at", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.Column("finished_at", vigilai.db.types.Utc(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_run_after"), ["run_after"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_task"), ["task"], unique=False)

    op.create_table(
        "llm_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("llm_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_cache_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_cache_stage"), ["stage"], unique=False)

    op.create_table(
        "masked_columns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pattern", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pattern"),
    )
    op.create_table(
        "named_values",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("report_type", sa.String(length=40), nullable=False),
        sa.Column("sheet", sa.String(length=100), nullable=False),
        sa.Column(
            "locator",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("named_values", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_named_values_name"), ["name"], unique=True)

    op.create_table(
        "report_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("report_type", sa.String(length=40), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_type"),
    )
    op.create_table(
        "reverse_pass_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "kinds",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("checked", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("at", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_run_id"), ["run_id"], unique=False)

    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("customer_name", sa.String(length=200), nullable=False),
        sa.Column("order_number", sa.String(length=100), nullable=False),
        sa.Column("configuration_id", sa.String(length=200), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_stage", sa.String(length=30), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("rerun_reason", sa.Text(), nullable=False),
        sa.Column("cloned_from_id", sa.Integer(), nullable=True),
        sa.Column("config_last_modified", sa.String(length=64), nullable=False),
        sa.Column("rules_version", sa.Integer(), nullable=False),
        sa.Column("model_used", sa.String(length=200), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("created_at", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.Column("started_at", vigilai.db.types.Utc(timezone=True), nullable=True),
        sa.Column("finished_at", vigilai.db.types.Utc(timezone=True), nullable=True),
        sa.Column("expires_at", vigilai.db.types.Utc(timezone=True), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "top_issues",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cloned_from_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_runs_configuration_id"), ["configuration_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_customer_name"), ["customer_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_runs_input_fingerprint"), ["input_fingerprint"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_runs_order_number"), ["order_number"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)

    op.create_table(
        "config_elements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("element_id", sa.String(length=40), nullable=False),
        sa.Column("json_path", sa.String(length=500), nullable=False),
        sa.Column("req_type", sa.String(length=40), nullable=False),
        sa.Column(
            "element",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_technical", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("config_elements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_config_elements_element_id"), ["element_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_config_elements_run_id"), ["run_id"], unique=False)

    op.create_table(
        "final_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("html_path", sa.String(length=500), nullable=False),
        sa.Column("pdf_path", sa.String(length=500), nullable=False),
        sa.Column("html_sha256", sa.String(length=64), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=False),
        sa.Column("generated_by", sa.String(length=200), nullable=False),
        sa.Column("generated_at", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("final_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_final_reports_run_id"), ["run_id"], unique=True)

    op.create_table(
        "findings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("finding_id", sa.String(length=40), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("leg", sa.String(length=30), nullable=False),
        sa.Column("rule_ref", sa.String(length=40), nullable=False),
        sa.Column("element_ref", sa.String(length=40), nullable=False),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("rules_version", sa.Integer(), nullable=False),
        sa.Column("review_status", sa.String(length=30), nullable=False),
        sa.Column("review_note", sa.Text(), nullable=False),
        sa.Column("reviewed_at", vigilai.db.types.Utc(timezone=True), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verify_agreed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_findings_review_status"), ["review_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_findings_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_severity"), ["severity"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_type"), ["type"], unique=False)

    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(length=200), nullable=False),
        sa.Column("created_at", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_calls_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_calls_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_calls_stage"), ["stage"], unique=False)

    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "rule",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("edited_by", sa.String(length=200), nullable=False),
        sa.Column("edited_at", vigilai.db.types.Utc(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rules_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rules_run_id"), ["run_id"], unique=False)

    op.create_table(
        "run_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("created_at", vigilai.db.types.Utc(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_files_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_run_files_sha256"), ["sha256"], unique=False)

    op.create_table(
        "run_stages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", vigilai.db.types.Utc(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("llm_calls", sa.Integer(), nullable=False),
        sa.Column("cache_hits", sa.Integer(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "stage", name="uq_run_stage"),
    )
    with op.batch_alter_table("run_stages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_stages_run_id"), ["run_id"], unique=False)

    op.create_table(
        "traces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.String(length=40), nullable=False),
        sa.Column("element_id", sa.String(length=40), nullable=True),
        sa.Column("verdict", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("by_code", sa.Boolean(), nullable=False),
        sa.Column("edited_by", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_traces_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_traces_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traces_run_id"))
        batch_op.drop_index(batch_op.f("ix_traces_rule_id"))

    op.drop_table("traces")
    with op.batch_alter_table("run_stages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_stages_run_id"))

    op.drop_table("run_stages")
    with op.batch_alter_table("run_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_files_sha256"))
        batch_op.drop_index(batch_op.f("ix_run_files_run_id"))

    op.drop_table("run_files")
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rules_run_id"))
        batch_op.drop_index(batch_op.f("ix_rules_rule_id"))

    op.drop_table("rules")
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_calls_stage"))
        batch_op.drop_index(batch_op.f("ix_llm_calls_run_id"))
        batch_op.drop_index(batch_op.f("ix_llm_calls_created_at"))

    op.drop_table("llm_calls")
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_findings_type"))
        batch_op.drop_index(batch_op.f("ix_findings_severity"))
        batch_op.drop_index(batch_op.f("ix_findings_run_id"))
        batch_op.drop_index(batch_op.f("ix_findings_review_status"))

    op.drop_table("findings")
    with op.batch_alter_table("final_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_final_reports_run_id"))

    op.drop_table("final_reports")
    with op.batch_alter_table("config_elements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_config_elements_run_id"))
        batch_op.drop_index(batch_op.f("ix_config_elements_element_id"))

    op.drop_table("config_elements")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_order_number"))
        batch_op.drop_index(batch_op.f("ix_runs_input_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_runs_expires_at"))
        batch_op.drop_index(batch_op.f("ix_runs_customer_name"))
        batch_op.drop_index(batch_op.f("ix_runs_created_at"))
        batch_op.drop_index(batch_op.f("ix_runs_configuration_id"))

    op.drop_table("runs")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_run_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_at"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    op.drop_table("users")
    op.drop_table("reverse_pass_categories")
    op.drop_table("report_templates")
    with op.batch_alter_table("named_values", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_named_values_name"))

    op.drop_table("named_values")
    op.drop_table("masked_columns")
    with op.batch_alter_table("llm_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_cache_stage"))
        batch_op.drop_index(batch_op.f("ix_llm_cache_created_at"))

    op.drop_table("llm_cache")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_task"))
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_run_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_run_after"))
        batch_op.drop_index(batch_op.f("ix_jobs_created_at"))

    op.drop_table("jobs")
    with op.batch_alter_table("configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_configs_sha256"))
        batch_op.drop_index(batch_op.f("ix_configs_configuration_id"))

    op.drop_table("configs")
    op.drop_table("compliance_rules")
    with op.batch_alter_table("check_definitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_check_definitions_name"))
        batch_op.drop_index(batch_op.f("ix_check_definitions_is_active"))

    op.drop_table("check_definitions")
    with op.batch_alter_table("attribute_aliases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attribute_aliases_canonical_name"))
        batch_op.drop_index(batch_op.f("ix_attribute_aliases_alias"))

    op.drop_table("attribute_aliases")
    # ### end Alembic commands ###
