"""artifact types and run scopes

Revision ID: 7055ed7523c8
Revises: 5754a730ad63
Created: 2026-09-18 15:54:02.402261

Additive changes only, portable across SQLite and Postgres (ADR-017).
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# Autogenerated migrations name our custom column types by their full path.
import greenlight_ai.db.types  # noqa: F401 - referenced by name in the column definitions

revision: str = "7055ed7523c8"
down_revision: Union[str, None] = "5754a730ad63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the change."""
    op.create_table(
        "artifact_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("ai_context", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", greenlight_ai.db.types.Utc(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artifact_types", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_artifact_types_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_artifact_types_key"), ["key"], unique=True)
        batch_op.create_index(batch_op.f("ix_artifact_types_kind"), ["kind"], unique=False)

    op.create_table(
        "run_scopes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("standing_instructions", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run_scopes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_scopes_code"), ["code"], unique=True)

    op.drop_table("report_templates")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scope", sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column("has_suppressions", sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f("ix_runs_scope"), ["scope"], unique=False)


def downgrade() -> None:
    """Revert the change."""
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_scope"))
        batch_op.drop_column("has_suppressions")
        batch_op.drop_column("scope")

    op.create_table(
        "report_templates",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("report_type", sa.VARCHAR(length=40), nullable=False),
        sa.Column("filename", sa.VARCHAR(length=500), nullable=False),
        sa.Column("storage_path", sa.VARCHAR(length=500), nullable=False),
        sa.Column("notes", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_type"),
    )
    with op.batch_alter_table("run_scopes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_scopes_code"))

    op.drop_table("run_scopes")
    with op.batch_alter_table("artifact_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifact_types_kind"))
        batch_op.drop_index(batch_op.f("ix_artifact_types_key"))
        batch_op.drop_index(batch_op.f("ix_artifact_types_is_active"))

    op.drop_table("artifact_types")
