"""accounts, sessions, and attribution

Revision ID: baaae6a37f72
Revises: 7055ed7523c8
Created: 2026-09-18

Additive, portable across SQLite and Postgres (ADR-017). Two things the autogenerated
draft got wrong and this corrects: every foreign key is named, because SQLite rebuilds
a table to add one and cannot drop an anonymous constraint later, and every new
NOT NULL column arrives with a server default so an existing row can satisfy it. The
defaults are dropped immediately afterwards, so the application stays the only thing
that decides a value.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import greenlight_ai.db.types  # noqa: F401 - referenced by name in the column definitions

revision: str = "baaae6a37f72"
down_revision: Union[str, None] = "7055ed7523c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the change."""
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=30), nullable=False),
        sa.Column("created_at", greenlight_ai.db.types.Utc(timezone=True), nullable=False),
        sa.Column("last_seen_at", greenlight_ai.db.types.Utc(timezone=True), nullable=False),
        sa.Column("expires_at", greenlight_ai.db.types.Utc(timezone=True), nullable=False),
        sa.Column("revoked_at", greenlight_ai.db.types.Utc(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_sessions_user_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sessions_expires_at", ["expires_at"], unique=False)
        batch_op.create_index("ix_sessions_token_hash", ["token_hash"], unique=True)
        batch_op.create_index("ix_sessions_user_id", ["user_id"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("username", sa.String(length=100), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column(
                "must_change_password", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column("is_placeholder", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column("last_login_at", greenlight_ai.db.types.Utc(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("failed_attempts", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("locked_until", greenlight_ai.db.types.Utc(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("deactivated_at", greenlight_ai.db.types.Utc(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("created_by_user_id", sa.Integer(), nullable=True))
        batch_op.create_index("ix_users_is_placeholder", ["is_placeholder"], unique=False)
        batch_op.create_index("ix_users_username", ["username"], unique=True)
        batch_op.create_foreign_key(
            "fk_users_created_by_user_id", "users", ["created_by_user_id"], ["id"]
        )
        batch_op.alter_column("username", server_default=None)
        batch_op.alter_column("must_change_password", server_default=None)
        batch_op.alter_column("is_placeholder", server_default=None)
        batch_op.alter_column("failed_attempts", server_default=None)

    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("actor", sa.String(length=200), nullable=False, server_default="")
        )
        batch_op.alter_column("actor", server_default=None)

    with op.batch_alter_table("configs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by_user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_configs_created_by_user_id", "users", ["created_by_user_id"], ["id"]
        )

    with op.batch_alter_table("final_reports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("generated_by_user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_final_reports_generated_by_user_id", "users", ["generated_by_user_id"], ["id"]
        )

    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_findings_reviewed_by_user_id", "users", ["reviewed_by_user_id"], ["id"]
        )

    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index("ix_runs_user_id", ["user_id"], unique=False)


def downgrade() -> None:
    """Revert the change."""
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index("ix_runs_user_id")

    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_constraint("fk_findings_reviewed_by_user_id", type_="foreignkey")
        batch_op.drop_column("reviewed_by_user_id")

    with op.batch_alter_table("final_reports", schema=None) as batch_op:
        batch_op.drop_constraint("fk_final_reports_generated_by_user_id", type_="foreignkey")
        batch_op.drop_column("generated_by_user_id")

    with op.batch_alter_table("configs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_configs_created_by_user_id", type_="foreignkey")
        batch_op.drop_column("created_by_user_id")

    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_column("actor")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users_created_by_user_id", type_="foreignkey")
        batch_op.drop_index("ix_users_username")
        batch_op.drop_index("ix_users_is_placeholder")
        batch_op.drop_column("created_by_user_id")
        batch_op.drop_column("deactivated_at")
        batch_op.drop_column("locked_until")
        batch_op.drop_column("failed_attempts")
        batch_op.drop_column("last_login_at")
        batch_op.drop_column("is_placeholder")
        batch_op.drop_column("must_change_password")
        batch_op.drop_column("username")

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_sessions_user_id")
        batch_op.drop_index("ix_sessions_token_hash")
        batch_op.drop_index("ix_sessions_expires_at")

    op.drop_table("sessions")
